
/* Drop Tables */

DROP TABLE MC_COMMENT CASCADE CONSTRAINTS;
DROP TABLE MC_BOARD CASCADE CONSTRAINTS;
DROP TABLE MC_ATTACHFILE CASCADE CONSTRAINTS;
DROP TABLE MC_AUTHORITY_MEMBER CASCADE CONSTRAINTS;
DROP TABLE MC_AUTHORITY CASCADE CONSTRAINTS;
DROP TABLE MC_MEMBER CASCADE CONSTRAINTS;




/* Create Tables */

-- 파일 정보
CREATE TABLE MC_ATTACHFILE
(
	-- 첨부파일 일련번호
	ATTACHFILE_SEQ varchar2(40) NOT NULL,
	-- 원본레코드 UNIQUE SEQ
	SOURCE_UNIQUE_SEQ varchar2(40) NOT NULL,
	-- 첨부파일 유형
	ATTACHFILE_TYPE varchar2(40),
	-- 원본 파일명
	ORGINALFILE_NAME varchar2(200) NOT NULL,
	-- 첨부 파일명
	PHYSICALFILE_NAME varchar2(200) NOT NULL,
	-- 썸네일 첨부파일명
	THUMBNAIL_NAME varchar2(500),
	-- 첨부파일 저장경로
	ATTACHFILE_PATH varchar2(500),
	-- 첨부파일 크기
	ATTACHFILE_SIZE number,
	-- 파일 높이
	ATTACHFILE_HEIGHT number,
	-- 파일 폭
	ATTACHFILE_WIDTH number,
	-- 등록자SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- 등록일자
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- 수정자_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- 수정일자
	MODIFY_DATE varchar2(20) NOT NULL,
	PRIMARY KEY (ATTACHFILE_SEQ)
);


-- 권한 종류
CREATE TABLE MC_AUTHORITY
(
	-- 권한 코드
	AUTHORITY_ID varchar2(40) NOT NULL,
	-- 명칭
	NAME varchar2(1000) NOT NULL,
	-- 코드설명
	DESCRIPTION varchar2(1000),
	-- 사용 여부
	USE_YN varchar2(40) NOT NULL,
	-- 등록자SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- 등록일자
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- 수정자_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- 수정일자
	MODIFY_DATE varchar2(20) NOT NULL,
	PRIMARY KEY (AUTHORITY_ID)
);


-- 사용자별 권한들
CREATE TABLE MC_AUTHORITY_MEMBER
(
	-- 권한 코드
	AUTHORITY_ID varchar2(40) NOT NULL,
	-- 회원_SEQ
	MEMBER_SEQ varchar2(40) NOT NULL,
	-- 등록자SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- 등록일자
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- 수정자_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- 수정일자
	MODIFY_DATE varchar2(20) NOT NULL,
	UNIQUE (AUTHORITY_ID, MEMBER_SEQ)
);


-- 게시판
CREATE TABLE MC_BOARD
(
	-- 게시물 일련번호
	MC_BOARD_SEQ varchar2(40) NOT NULL,
	-- 제목
	TITLE varchar2(4000) NOT NULL,
	-- 내용
	CONTENT varchar2(4000) NOT NULL,
	-- 시작일시 (공지 등)
	START_DATE varchar2(20),
	-- 종료일시 (공지 등)
	END_DATE varchar2(20),
	-- 첨부 파일
	ITEM varchar2(2000),
	-- 대분류
	CATEGORY varchar2(40) NOT NULL,
	-- 등록자SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- 등록일자
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- 수정자_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- 수정일자
	MODIFY_DATE varchar2(20) NOT NULL,
	-- 권한 코드
	AUTHORITY_ID varchar2(40) NOT NULL,
	-- 회원_SEQ
	MEMBER_SEQ varchar2(40) NOT NULL,
	-- 첨부파일 일련번호
	ATTACHFILE_SEQ varchar2(40),
	CONSTRAINT PK_MULTI1501_BOARD PRIMARY KEY (MC_BOARD_SEQ)
);


-- 댓글
CREATE TABLE MC_COMMENT
(
	-- 게시물 일련번호
	MC_BOARD_SEQ varchar2(40) NOT NULL,
	-- 회원_SEQ
	MEMBER_SEQ varchar2(40) NOT NULL,
	-- 댓글
	CONTENT varchar2(4000)
);


-- 회원정보
CREATE TABLE MC_MEMBER
(
	-- 회원_SEQ
	MEMBER_SEQ varchar2(40) NOT NULL,
	-- EMAIL
	EMAIL varchar2(1000),
	-- 암호
	PASSWORD varchar2(100) NOT NULL,
	-- 이름
	NAME varchar2(40) NOT NULL,
	-- 지역
	Adress varchar2(1000) NOT NULL,
	-- 관심분야
	Interest varchar2(1000) DEFAULT '없음',
	-- 등록자SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- 등록일자
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- 수정자_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- 수정일자
	MODIFY_DATE varchar2(20) NOT NULL,
	PRIMARY KEY (MEMBER_SEQ)
);



/* Create Foreign Keys */

ALTER TABLE MC_BOARD
	ADD FOREIGN KEY (ATTACHFILE_SEQ)
	REFERENCES MC_ATTACHFILE (ATTACHFILE_SEQ)
;


ALTER TABLE MC_AUTHORITY_MEMBER
	ADD FOREIGN KEY (AUTHORITY_ID)
	REFERENCES MC_AUTHORITY (AUTHORITY_ID)
;


ALTER TABLE MC_BOARD
	ADD FOREIGN KEY (AUTHORITY_ID, MEMBER_SEQ)
	REFERENCES MC_AUTHORITY_MEMBER (AUTHORITY_ID, MEMBER_SEQ)
;


ALTER TABLE MC_COMMENT
	ADD FOREIGN KEY (MC_BOARD_SEQ)
	REFERENCES MC_BOARD (MC_BOARD_SEQ)
;


ALTER TABLE MC_AUTHORITY_MEMBER
	ADD FOREIGN KEY (MEMBER_SEQ)
	REFERENCES MC_MEMBER (MEMBER_SEQ)
;


ALTER TABLE MC_COMMENT
	ADD FOREIGN KEY (MEMBER_SEQ)
	REFERENCES MC_MEMBER (MEMBER_SEQ)
;



/* Comments */

COMMENT ON TABLE MC_ATTACHFILE IS '파일 정보';
COMMENT ON COLUMN MC_ATTACHFILE.ATTACHFILE_SEQ IS '첨부파일 일련번호';
COMMENT ON COLUMN MC_ATTACHFILE.SOURCE_UNIQUE_SEQ IS '원본레코드 UNIQUE SEQ';
COMMENT ON COLUMN MC_ATTACHFILE.ATTACHFILE_TYPE IS '첨부파일 유형';
COMMENT ON COLUMN MC_ATTACHFILE.ORGINALFILE_NAME IS '원본 파일명';
COMMENT ON COLUMN MC_ATTACHFILE.PHYSICALFILE_NAME IS '첨부 파일명';
COMMENT ON COLUMN MC_ATTACHFILE.THUMBNAIL_NAME IS '썸네일 첨부파일명';
COMMENT ON COLUMN MC_ATTACHFILE.ATTACHFILE_PATH IS '첨부파일 저장경로';
COMMENT ON COLUMN MC_ATTACHFILE.ATTACHFILE_SIZE IS '첨부파일 크기';
COMMENT ON COLUMN MC_ATTACHFILE.ATTACHFILE_HEIGHT IS '파일 높이';
COMMENT ON COLUMN MC_ATTACHFILE.ATTACHFILE_WIDTH IS '파일 폭';
COMMENT ON COLUMN MC_ATTACHFILE.REGISTER_SEQ IS '등록자SEQ';
COMMENT ON COLUMN MC_ATTACHFILE.REGISTRY_DATE IS '등록일자';
COMMENT ON COLUMN MC_ATTACHFILE.MODIFIER_SEQ IS '수정자_SEQ';
COMMENT ON COLUMN MC_ATTACHFILE.MODIFY_DATE IS '수정일자';
COMMENT ON TABLE MC_AUTHORITY IS '권한 종류';
COMMENT ON COLUMN MC_AUTHORITY.AUTHORITY_ID IS '권한 코드';
COMMENT ON COLUMN MC_AUTHORITY.NAME IS '명칭';
COMMENT ON COLUMN MC_AUTHORITY.DESCRIPTION IS '코드설명';
COMMENT ON COLUMN MC_AUTHORITY.USE_YN IS '사용 여부';
COMMENT ON COLUMN MC_AUTHORITY.REGISTER_SEQ IS '등록자SEQ';
COMMENT ON COLUMN MC_AUTHORITY.REGISTRY_DATE IS '등록일자';
COMMENT ON COLUMN MC_AUTHORITY.MODIFIER_SEQ IS '수정자_SEQ';
COMMENT ON COLUMN MC_AUTHORITY.MODIFY_DATE IS '수정일자';
COMMENT ON TABLE MC_AUTHORITY_MEMBER IS '사용자별 권한들';
COMMENT ON COLUMN MC_AUTHORITY_MEMBER.AUTHORITY_ID IS '권한 코드';
COMMENT ON COLUMN MC_AUTHORITY_MEMBER.MEMBER_SEQ IS '회원_SEQ';
COMMENT ON COLUMN MC_AUTHORITY_MEMBER.REGISTER_SEQ IS '등록자SEQ';
COMMENT ON COLUMN MC_AUTHORITY_MEMBER.REGISTRY_DATE IS '등록일자';
COMMENT ON COLUMN MC_AUTHORITY_MEMBER.MODIFIER_SEQ IS '수정자_SEQ';
COMMENT ON COLUMN MC_AUTHORITY_MEMBER.MODIFY_DATE IS '수정일자';
COMMENT ON TABLE MC_BOARD IS '게시판';
COMMENT ON COLUMN MC_BOARD.MC_BOARD_SEQ IS '게시물 일련번호';
COMMENT ON COLUMN MC_BOARD.TITLE IS '제목';
COMMENT ON COLUMN MC_BOARD.CONTENT IS '내용';
COMMENT ON COLUMN MC_BOARD.START_DATE IS '시작일시 (공지 등)';
COMMENT ON COLUMN MC_BOARD.END_DATE IS '종료일시 (공지 등)';
COMMENT ON COLUMN MC_BOARD.ITEM IS '첨부 파일';
COMMENT ON COLUMN MC_BOARD.CATEGORY IS '대분류';
COMMENT ON COLUMN MC_BOARD.REGISTER_SEQ IS '등록자SEQ';
COMMENT ON COLUMN MC_BOARD.REGISTRY_DATE IS '등록일자';
COMMENT ON COLUMN MC_BOARD.MODIFIER_SEQ IS '수정자_SEQ';
COMMENT ON COLUMN MC_BOARD.MODIFY_DATE IS '수정일자';
COMMENT ON COLUMN MC_BOARD.AUTHORITY_ID IS '권한 코드';
COMMENT ON COLUMN MC_BOARD.MEMBER_SEQ IS '회원_SEQ';
COMMENT ON COLUMN MC_BOARD.ATTACHFILE_SEQ IS '첨부파일 일련번호';
COMMENT ON TABLE MC_COMMENT IS '댓글';
COMMENT ON COLUMN MC_COMMENT.MC_BOARD_SEQ IS '게시물 일련번호';
COMMENT ON COLUMN MC_COMMENT.MEMBER_SEQ IS '회원_SEQ';
COMMENT ON COLUMN MC_COMMENT.CONTENT IS '댓글';
COMMENT ON TABLE MC_MEMBER IS '회원정보';
COMMENT ON COLUMN MC_MEMBER.MEMBER_SEQ IS '회원_SEQ';
COMMENT ON COLUMN MC_MEMBER.EMAIL IS 'EMAIL';
COMMENT ON COLUMN MC_MEMBER.PASSWORD IS '암호';
COMMENT ON COLUMN MC_MEMBER.NAME IS '이름';
COMMENT ON COLUMN MC_MEMBER.Adress IS '지역';
COMMENT ON COLUMN MC_MEMBER.Interest IS '관심분야';
COMMENT ON COLUMN MC_MEMBER.REGISTER_SEQ IS '등록자SEQ';
COMMENT ON COLUMN MC_MEMBER.REGISTRY_DATE IS '등록일자';
COMMENT ON COLUMN MC_MEMBER.MODIFIER_SEQ IS '수정자_SEQ';
COMMENT ON COLUMN MC_MEMBER.MODIFY_DATE IS '수정일자';



